### PR TITLE
update for v1.2.0, add provenance script in docker compose

### PR DESCRIPTION
**Pull request by tloubrieu-jpl**
## 🗒️ Summary
- Update version number of registry-api.
- Update test suite
- Add provenance script to docker compose

## ⚙️ Test Data and/or Report
Run the integration tests with:

     docker compose --profile=int-registry-batch-loader up

## ♻️ Related Issues

Fixes https://github.com/NASA-PDS/registry/issues/140

### CODE REVIEW

**Comment by nutjob4life** [comment]
@tloubrieu-jpl is either of the following available?

- Reference to regression test included in code (preferred wherever reasonable)
- Attach test data here + outputs of tests

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life , I added the missing information on the integration tests. Thanks for making this pull request better.

Thomas

**Review by nutjob4life — APPROVED** [review]
👍

**Comment by nutjob4life** [comment]
> Hi @nutjob4life , I added the missing information on the integration tests. Thanks for making this pull request better.

Thanks @tloubrieu-jpl !

**Pull request merged**
