### PR TITLE
484 485 486 487 Membership latest tests

### PR DESCRIPTION
**Pull request by alexdunnjpl**
## 🗒️ Summary
Implement tests
Adds default docker credentials for ease of development

## ⚙️ Test Data and/or Report
Adds new tests and trivially-modifies a couple of others. All relevant tests pass

## ♻️ Related Issues
fixes https://github.com/NASA-PDS/registry-api/issues/484
fixes https://github.com/NASA-PDS/registry-api/issues/485
fixes https://github.com/NASA-PDS/registry-api/issues/486
fixes https://github.com/NASA-PDS/registry-api/issues/487

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
👍

**Comment by alexdunnjpl** [comment]
Postpone merge until resolution of #300

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl @nutjob4life could I please get a second/third pair of eyes on the fixes derived from #300 ?

https://github.com/NASA-PDS/registry/pull/299/commits/c25cd8f0e2ade988333c6d25b6409642c162e347

I've triple-checked the changes and run the updated tests to confirm they pass, but wouldn't hurt.

**Review by tloubrieu-jpl — APPROVED** [review]
ok, let's move on with that.

**Comment by nutjob4life** [comment]
> @tloubrieu-jpl @nutjob4life could I please get a second/third pair of eyes on the fixes derived from #300 ?
> 
> [c25cd8f](https://github.com/NASA-PDS/registry/commit/c25cd8f0e2ade988333c6d25b6409642c162e347)
> 
> I've triple-checked the changes and run the updated tests to confirm they pass, but wouldn't hurt.

Nothing jumps out at me … let's go for it

**Pull request merged**
